### PR TITLE
Db changes

### PR DESCRIPTION
**Pull request by jjonas3**
Changes as requested.  More to come!

### CODE REVIEW

**Comment by johnpankowicz** [comment]
Sorry, but I needed to not accept the PR. The initial purpose of this change was to remove the location related properties from GovernmentBody and put them in their own class:

```
public string Country { get; set; }
public string State { get; set; }
public string County { get; set; }
public string Municipality { get; set; }
```

You did that in your first commit, when you removed these properties from the renamed class GovBody. But then in the process of trying to get the code to build, you ending up putting all these same properties back into the GovBody class!

**Comment by johnpankowicz** [comment]
Sorry, but I need to not accept the PR. The initial purpose of this change was to remove the location related properties from GovernmentBody and put them in their own class:

public string Country { get; set; }
public string State { get; set; }
public string County { get; set; }
public string Municipality { get; set; }

You did that in your first commit, when you removed these properties from the renamed class GovBody. But then in the process of trying to get the code to build, you ending up putting all these same properties back into the GovBody class!

**Comment by jjonas3** [comment]
I did. I thought you needed something to build quick. I can fix it

This email signature space available for rent. Inquire within.

On Aug 30, 2020, at 7:08 AM, johnpankowicz <notifications@github.com> wrote:

﻿

Sorry, but I need to not accept the PR. The initial purpose of this change was to remove the location related properties from GovernmentBody and put them in their own class:

public string Country { get; set; }
public string State { get; set; }
public string County { get; set; }
public string Municipality { get; set; }

You did that in your first commit, when you removed these properties from the renamed class GovBody. But then in the process of trying to get the code to build, you ending up putting all these same properties back into the GovBody class!

**Comment by johnpankowicz** [comment]
I already took the code from your 1st commit "Model changes" and merged that in. So, I'll close this PR.

I've been fixing the backend code. It was very messy. There was a lot of legacy code and a lot of code that was written fast and should have been refactored long ago. I should be done in a few days.

**Pull request closed without merging**
